### PR TITLE
Make connection pool configurable

### PR DESCRIPTION
**Pull request by humengyu2012**

### CODE REVIEW

**Comment by xuanyu66** [comment]
@humengyu2012 please add some description

**Comment by humengyu2012** [comment]
TiDB connector has a built-in JDBC connection pool implemented by HikariCP, which is useful for long running application such as presto, trino. But connection pool is too heavy for per job application such as flink, mapreduce. So I think it should be configurable.

**Comment by xuanyu66** [comment]
> TiBigData has a built-in JDBC connection pool implemented by HikariCP, which is useful for long running application such as presto, trino. But connection pool is too heavy for per job application such as flink, mapreduce. So I think it should be configurable.

Also, need some docs to introduce how to configure.

**Comment by xuanyu66** [comment]
LGTM

**Review by xuanyu66 — APPROVED** [review]

**Review by sunxiaoguang — APPROVED** [review]

**Pull request merged**
