### PR TITLE
use recommend mySQL driver.

### PR DESCRIPTION
**Pull request by LittleFall**
change `MYSQL_DRIVER_NAME` from `com.mysql.jdbc.Driver` to `com.mysql.cj.jdbc.Driver`.

solve https://github.com/tidb-incubator/TiBigData/issues/49

### CODE REVIEW

**Review by marsishandsome — APPROVED** [review]
LGTM

**Comment by humengyu2012** [comment]
For mysql driver with version 5.X, the driver class name is 'com.mysql.jdbc.Driver'. If we rename 'com.mysql.jdbc.Driver' to 'com.mysql.cj.jdbc.Driver' and use a lower version mysql driver, we will get a calss not found exception.

**Comment by LittleFall** [comment]
> For mysql driver with version 5.X, the driver class name is 'com.mysql.jdbc.Driver'. If we rename 'com.mysql.jdbc.Driver' to 'com.mysql.cj.jdbc.Driver' and use a lower version mysql driver, we will get a calss not found exception. 'com.mysql.jdbc.Driver' will give us a warning although it could compatible with all mysql driver versions. Do we have a better way to solve it?

Thank you for your carefulness. I will explore if there is a more suitable solution.

**Pull request closed without merging**
