### PR TITLE
support integration test

### PR DESCRIPTION
**Pull request by marsishandsome**
close https://github.com/tidb-incubator/TiBigData/issues/43

support running integration test
```
TIDB_URL="jdbc:tidb://127.0.0.1:4000?user=root&password="
mvn clean test -am -pl flink
mvn clean test -am -pl prestodb
mvn clean test -am -pl jdbc
```

### CODE REVIEW

**Comment by marsishandsome** [comment]
@humengyu2012 @sunxiaoguang PTAL

**Review by sunxiaoguang — APPROVED** [review]
LGTM

**Pull request merged**
