### PR TITLE
driver: compatible with old and new mysql jdbc drivers

### PR DESCRIPTION
**Pull request by Al-assad**
Compatible with old and new jdbc drivers.
Using the new mysql jdbc driver(com.mysql.cj.jdbc.Driver) by default. When the com.mysql.cj.jdbc.Driver cannot be found, it will automatically switch to the old jdbc driver(com.mysql.jdbc.Driver).

### CODE REVIEW

**Comment by sunxiaoguang** [comment]
There is a lint warning that you have to fix.

image

**Comment by Al-assad** [comment]
> There is a lint warning that you have to fix.
> 
> image



> There is a lint warning that you have to fix.
> 
> image

yep the code formatting checker is pretty strict 😅

**Comment by Al-assad** [comment]
> There is a lint warning that you have to fix.
> 
> image

yep the code formatting checker is pretty strict 😅

**Comment by sunxiaoguang** [comment]
LGTM

**Review by sunxiaoguang — APPROVED** [review]

**Pull request merged**
