### PR TITLE
Upgrade `tikv-client-java` version from `3.2.0-SNAPSHOT` to `3.2.0`

### PR DESCRIPTION
**Pull request by pyscala**
Upgrade tikv-client-java version from 3.2.0-SNAPSHOT to 3.2.0

### CODE REVIEW

**Comment by humengyu2012** [comment]
Could you delete the script for building client-java. https://github.com/tidb-incubator/TiBigData/blob/master/.ci/build-client-java.sh

**Comment by pyscala** [comment]
> 
Hi,  Delete this file?

**Comment by pyscala** [comment]
@humengyu2012 , thanks for your replay.

**Comment by humengyu2012** [comment]
This PR seems good to me. Could you also delete the decriptions of client-java in readme of flink/hive/presto? 

image


image

**Comment by pyscala** [comment]
> This PR seems good to me. Could you also delete the decriptions of client-java in readme of flink/hive/presto?
> 
> image
> 
> image

done, review again.

**Comment by humengyu2012** [comment]
@pyscala Presto, Trino and Hive also need.

**Comment by pyscala** [comment]
> 



> @pyscala Presto, Trino and Hive also need.

@humengyu2012, anything else？

**Comment by humengyu2012** [comment]
The readme.md of presto/prestosql/trino/hive also need delete the descriptions of client-java, not only flink.

**Comment by pyscala** [comment]
Done. review again, please.

**Comment by humengyu2012** [comment]
Good job, LGTM.

**Review by humengyu2012 — APPROVED** [review]
Good job, LGTM.

**Review by sunxiaoguang — APPROVED** [review]
LGTM

**Pull request merged**
