### PR TITLE
[flink-tidb-connector] use the exception classes from `flink-table-common.jar` instead of `flink-table-planner.jar`

### PR DESCRIPTION
**Pull request by itinycheng**
1. make the `flink-tidb-connector` independent from `flink-table-planner.jar`, because it's an optional jar.
2. after step 1, users can freely choose which planner they need without depending on `flink-table-planner.jar`.

### CODE REVIEW

**Review by sunxiaoguang — COMMENTED** [review]
@humengyu2012 PTAL

**Comment by humengyu2012** [comment]
LGTM

**Review by humengyu2012 — APPROVED** [review]

**Comment by sunxiaoguang** [comment]
LGTM

**Pull request merged**
