### PR TITLE
Additional support for Flink Catalog for PR#86

### PR DESCRIPTION
**Pull request by Al-assad**
Signed-off-by: Al-assad yulin.ying@outlook.com

### CODE REVIEW

**Comment by Al-assad** [comment]
@humengyu2012 @sunxiaoguang PTAL

**Comment by sunxiaoguang** [comment]
Looks like linter complained about an issue.

**Comment by Al-assad** [comment]
@sunxiaoguang Some code formatting issues, I've fixed it, PTAL again.
I will add an additional unit test in another PR, it seems that hybridsource has caused some of the original unit tests not to be fully applicable.

**Comment by sunxiaoguang** [comment]
Well I'm not sure if flink-base dependency introduces multiple version of flink dependencies. Can you do some investigation to make sure it doesn't cause runtime issue?

**Comment by sunxiaoguang** [comment]
@Al-assad In case you didn't get notified, can you help investigate if there are binary compatibility issue when depending on flink-base which is built with flink-1.11

**Comment by Al-assad** [comment]
@sunxiaoguang AFAIK there are no fatal compilation compatibility issues, I'll get back to you later with details

**Comment by Al-assad** [comment]
The compatibility issues of flink-base based on flink-1.11 for 1.13 are mainly focused on io.tidb.bigdata.flink.tidb.TiDBBaseCatalogFactory, which contains the following 2 points:

1. The constant `CATALOG_TYPE`、`CATALOG_PROPERTY_VERSION` has been removed in flink-1.13, but is safe because it is replaced with literal at the compile stage, both of which are identical in flink-1.11 and 1.13.
Pasted Graphic 1

2. The `CatalogFactory` interface has been marked as deprecated in Flink-1.13 by the requiredContext, supportedProperties methods and moved its functionality to the `Factory` interface. So I re-inherited the `Factory` implementation from [TiDBCatalogFactory](flink/flink-1.13/src/main/java/io/tidb/bigdata/flink/connector/catalog/TiDBCatalogFactory.java) in Flink-1.13 connector.
* [CatalogFactory in Flink-1.13](https://github.com/apache/flink/blob/release-1.13/flink-table/flink-table-common/src/main/java/org/apache/flink/table/factories/CatalogFactory.java)
* [CatalogFactory in Flink-1.11](https://github.com/apache/flink/blob/release-1.11/flink-table/flink-table-common/src/main/java/org/apache/flink/table/factories/CatalogFactory.java)

**Comment by Al-assad** [comment]
What's more, the flink-related dependencies introduced by [flink/flink-base](https://github.com/tidb-incubator/TiBigData/blob/master/flink/flink-base/pom.xml) are provided scope and do not introduce flink multi-version dependencies in the final compiled binary package

**Comment by sunxiaoguang** [comment]
@Al-assad thanks for your investigation. Since there is no binary compatibility issue in Catalog interface, we should be safe.

> The compatibility issues of flink-base based on flink-1.11 for 1.13 are mainly focused on io.tidb.bigdata.flink.tidb.TiDBBaseCatalogFactory, which contains the following 2 points:
> 
> 1. The constant `CATALOG_TYPE`、`CATALOG_PROPERTY_VERSION` has been removed in flink-1.13, but is safe because it is replaced with literal at the compile stage, both of which are identical in flink-1.11 and 1.13.
> 
> Pasted Graphic 1
> 
> 1. The `CatalogFactory` interface has been marked as deprecated in Flink-1.13 by the requiredContext, supportedProperties methods and moved its functionality to the `Factory` interface. So I re-inherited the `Factory` implementation from [TiDBCatalogFactory](flink/flink-1.13/src/main/java/io/tidb/bigdata/flink/connector/catalog/TiDBCatalogFactory.java) in Flink-1.13 connector.
> 
> * [CatalogFactory in Flink-1.13](https://github.com/apache/flink/blob/release-1.13/flink-table/flink-table-common/src/main/java/org/apache/flink/table/factories/CatalogFactory.java)
> * [CatalogFactory in Flink-1.11](https://github.com/apache/flink/blob/release-1.11/flink-table/flink-table-common/src/main/java/org/apache/flink/table/factories/CatalogFactory.java)

**Comment by sunxiaoguang** [comment]
@Al-assad  Another quick question, since CatalogFactory extends Factory since 1.13, maybe we should remove service definition in org.apache.flink.table.factories.TableFactory and put it into org.apache.flink.table.factories.Factory. Can you verify if that works as we expected? Thanks.


> The compatibility issues of flink-base based on flink-1.11 for 1.13 are mainly focused on io.tidb.bigdata.flink.tidb.TiDBBaseCatalogFactory, which contains the following 2 points:
> 
> 1. The constant `CATALOG_TYPE`、`CATALOG_PROPERTY_VERSION` has been removed in flink-1.13, but is safe because it is replaced with literal at the compile stage, both of which are identical in flink-1.11 and 1.13.
> 
> Pasted Graphic 1
> 
> 1. The `CatalogFactory` interface has been marked as deprecated in Flink-1.13 by the requiredContext, supportedProperties methods and moved its functionality to the `Factory` interface. So I re-inherited the `Factory` implementation from [TiDBCatalogFactory](flink/flink-1.13/src/main/java/io/tidb/bigdata/flink/connector/catalog/TiDBCatalogFactory.java) in Flink-1.13 connector.
> 
> * [CatalogFactory in Flink-1.13](https://github.com/apache/flink/blob/release-1.13/flink-table/flink-table-common/src/main/java/org/apache/flink/table/factories/CatalogFactory.java)
> * [CatalogFactory in Flink-1.11](https://github.com/apache/flink/blob/release-1.11/flink-table/flink-table-common/src/main/java/org/apache/flink/table/factories/CatalogFactory.java)

**Comment by Al-assad** [comment]
@sunxiaoguang remove the service definition of org.apache.flink.table.facts.TableFactory is not necessary, flink-1.13 has already done the relevant transitional compatibility. Actually the closed PR#85 has been running on our production environment for a month now

**Comment by sunxiaoguang** [comment]
> @sunxiaoguang remove the service definition of org.apache.flink.table.facts.TableFactory is not necessary, flink-1.13 has already done the relevant transitional compatibility. Actually the closed PR#85 has been running on our production environment for a month now

Cool. I have no other comment about this PR now. Let's merge it.

**Comment by sunxiaoguang** [comment]
LGTM

**Review by sunxiaoguang — APPROVED** [review]

**Pull request merged**
